## Linear Algebra

* https://paper.dropbox.com/doc/Linear-Algebra-D53DmVmTzum4nEabztXtI

* Check blog post here: hhttps://medium.com/towards-data-science/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c
* And cheatsheet here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html
* http://www.geeksforgeeks.org/engineering-mathematics-tutorials/
* Approach
    * Implement basic operations from scratch and with numpy (or opencv)
    * Show examples of different types of matrices and when to use them
* https://stackoverflow.com/questions/32370281/how-to-include-image-or-picture-in-jupyter-notebook

## ToC

In [3]:
"""
1. Complete both inplace and extra memory solutions
2. Do things from scratch and with numpy

- Transpose a Matrix (First w extra memory, then in place)
- https://www.interviewbit.com/problems/set-matrix-zeros/
- Find element
- Get out of a maze
- Dot product
- Cross product
- Rotate a Matrix (90, 180, 45)
- Horizonal/Vertical Flip a matrix
- Resize/Scale a matrix
- Swirl ()
- Naive interpolation approach
- Zoom a matrix in/out
- Translate/shift a matrix
- IoU (Two rectangles, circles)
- Sum of all pixels inside a rectangle/circle (grayscale?)
- Basic operations on cube
    - Rotate
    - Connected cells
    - Find element
- https://github.com/bfortuner/boring-stuff/blob/master/recursion/python/connected_cells.py
- https://www.topcoder.com/community/data-science/data-science-tutorials/geometry-concepts-basic-concepts/
- https://www.topcoder.com/community/data-science/data-science-tutorials/geometry-concepts-line-intersection-and-its-applications/
"""

## Data

In [46]:
import numpy as np
from IPython.display import Image
from IPython.core.display import HTML

In [79]:
def P(in_arr, out_arr):
    print(in_arr)
    if type(out_arr) != np.ndarray:
        out_arr = np.array(out_arr)
    print(out_arr)
    print('---')

arr1 = np.array([[1]])
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
arr4 = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
squares = [arr1, arr2, arr3]
rects = [arr1, arr2, arr3, arr4]

## Basics

* First see Math notebook for preliminary definitions.
* Links
    * https://blog.stata.com/2011/03/03/understanding-matrices-intuitively-part-1/
    * https://blog.stata.com/2011/03/09/understanding-matrices-intuitively-part-2/
    * http://www.austinadee.com/wpblog/linear-transforms-and-eigenvectors/
    * http://stattrek.com/tutorials/matrix-algebra-tutorial.aspx
* Linear vs Non-Linear
![LL](https://study.com/cimages/multimages/16/linear_function_vs_nonlinear_function.png)
* Linear Transformation
    * A linear transformation preserves linear relationships between variables. 
    * Therefore, the correlation between x and y would be unchanged after a linear transformation.
    * Examples would be multiplying by a constant, dividing by a constant, or adding a constant.
    
* Nonlinear tranformation
    * A nonlinear transformation changes (increases or decreases) linear relationships between variables
    * It changes the correlation between variables
    * Examples include taking the square root or the reciprocal
* What is a Linear Transformation?
    * The output of the operation is still linear (straight)
        * Scaling inputs scales the output (multiplication)
        * Adding inputs adds the outputs (addition)
    * In geometry terms:
        * Linear Transformations shift, scale and rotate input
        * The origin must remain fixed, and all lines must remain lines?
    * Thinking of numbers as transformations gives an alternate interpretation of multiplication
    * https://www.khanacademy.org/math/linear-algebra/matrix-transformations/a/visualizing-linear-transformations/a/practice-associating-matrices-with-transformations/a/visualizing-linear-transformations
    * You can easily figure out which number is being multiplied into the line by following one.
* What is a Non-Learning Transformation?
    * Ouput of the operation is non-linear (not straight)
    * In geometry terms:
        * Non-linear transformations bend and twist input
* Systems of equations
    * http://stattrek.com/matrix-algebra/system-of-equations.aspx
* What's Linear Algebra?
    * Linear algebra is the study of vectors and linear functions that act on those vectors
    * Provides 2 things:
        * Storing groups of data points or equations
        * Manipulating groups of data points or solving sets of equations
    * Algebra for higher dimensional spaces (2D, 3D)
        * Basic Algebra provides tools for operating on scalars (points)
        * Linear Algebra provides tools for operating on lines and planes
    * Linear equations can "linearize" other mathematical objects by reducing or expanding the object into a space with linear properties.
* What's a mapping?
    * Association between members of one set and another set
    * Examples are Transformations, Functions and Relations
* What's a transformation?
    * A function a points in space
    * Rotation, Reflection, Translations
* What's a linear transformation?
    * A linear function on points in space
    * Preserves properties of addition and scalar multiplication
    * It does not matter whether you apply the linear map before or after addition or multiplication
* Primatives of Linear Algebra:
    * Vectors and matrices
    * Store groups of numbers or groups of transformations
* What's a vector?
    * A vector stores a proposed change to a line, or plane
        * 1D - [1] - add 2, [2x] means multiply by 2
        * 2D - [1 2] - add 1 to x axis, add 2 to y axis
        * 3D - [1 2 3] - add 1 to x, 2 to y, 3 to z
    * It stores magnitude and direction
    * It's a single, linear transformation
    * The larger the vector, the higher-dimensional the space
* What's a matrix?
    * Two definitions:
        1. A bunch of column vectors stacked side by side (data store)
        2. A group of linear functions (rows) acting on a vector (function store)
    * Matrix stores groups of numbers or groups of linear equations
    * It lets you solve multiple linear transformations
* What does it mean to combine linear transformations?
    * Chain them!
    * A(x) and B(x) = B(A(x))



What's matrix multiplication?
* Applying multiple linear transformations to an input
* Used for rotations, reflections, translations

Example: Combining Two Linear Transformations

In [61]:
"""
A(X) = [1] 
       [2]
B(X) = [3] 
       [4] 
Combined = B(A(X))
M   = [1 3]
      [2 4]
M.T = [1 2]   <- 1st column is operation on x axis, 2nd column is operation on y axis
      [3 4]
X = [3]
    [5]
Y = np.dot(M.T, X)
Y = rows of first, columns of second
    [3 5] * [1 2] = [3*1 + 5*3] = [18 26]
            [3 4]   [3*2 + 5*4]   



So what does this mean?
    * In the 1st operation, A = x*1, y*2
    * In the 2nd operation, B = x*3, y*2

""";


* Matrix transformations are ALWAYS linear!
    
* Matrix and Vector Operation
![Intuition 1](https://betterexplained.com/wp-content/uploads/images//linear-algebra-visualize-20121002-221620.png)

![Intuition 2](https://betterexplained.com/wp-content/uploads/images//linear-algebra-pour-20121002-220550.png)

* In Linear Algebra we can treat vectors/matrixes as data or functions
* Convention: 
    * Rows represent operations
    * Columns represent data
![image.png](https://betterexplained.com/wp-content/uploads/linear-algebra/standard-interpretation.png)

* But we can switch! Depending on desired outcome.
![image.png](https://betterexplained.com/wp-content/uploads/linear-algebra/code-data-equivalence.png)

* The matrix transpose lets us do this!
* We can have a single function on a single vector
![image.png](https://betterexplained.com/wp-content/uploads/linear-algebra/x-transform-x.png)

* Or multiple functions on multiple vectors
![image.png](https://betterexplained.com/wp-content/uploads/linear-algebra/x-x-trainsform.png)

* In machine learning we see this (weights.T * X input)
![ml](https://betterexplained.com/wp-content/plugins/wp-latexrender/pictures/35be34f0e97ad0faa6963c2ef3a523a9.png)
* This means the weights become the function we apply to the data
* We transpose the weights to turn the data (columns) into functions (rows)
    * This rearrangement is necessary to properly apply all the functions to all the data
* https://betterexplained.com/articles/matrix-multiplication/

* Matrix Multiplication
    * https://betterexplained.com/articles/matrix-multiplication/
    * Matrix product is nothing more than a book-keeping device for keeping track of the composition of linear transformations
    * We define product of matrices explicitly so that it will match up composition of linear transformations
    * https://math.stackexchange.com/questions/24456/matrix-multiplication-interpreting-and-understanding-the-process?noredirect=1&lq=1
    * https://www.khanacademy.org/math/linear-algebra/matrix-transformations/composition-of-transformations/v/compositions-of-linear-transformations-1

## Rotate

In [62]:
def rot90(arr):
    out = []
    col = 0
    while col < len(arr[0]):
        tmp = []
        row = len(arr)-1
        while row >= 0:
            tmp.append(arr[row][col])
            row -=1
        out.append(tmp)
        col += 1
    return out    

def rot180(arr):
    arr = rot90(arr)
    arr = rot90(arr)
    return arr

def rot90_inplace(arr):
    return arr

def rot90_np(arr):
    return np.rot90(arr, k=3)

arr1 = [
    [1]
]
arr2 = [
    [1,2],
    [3,4]
]

    [1,2],
    [3,4]

    [3,6]
    [4,7]

arr3 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

7 8 9
4 5 6
1 2 3

Goal ---
7 4 1
8 5 2
9 6 3

arr4 = [
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [14, 15, 16, 17],
]

"""
14 9  5 1
15 10 6 2
16 11 7 3
17 12 8 4
"""

arr4 = [
    [1, 2, 3],
    [4, 5, 6],
]
    
    
def rot90_inplace(arr):
    row,col = 0,0

IndentationError: unexpected indent (<ipython-input-62-8dec0c1c46c9>, line 33)

In [23]:
np.rot90??

In [37]:
for a in rects:
    print(np.array(rot90(a)))
for a in rects:
    print(np.array(rot180(a)))
for a in rects:
    print(rot90_np(a))

[[1]]
[[3 1]
 [4 2]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
[[4 1]
 [5 2]
 [6 3]]
[[1]]
[[4 3]
 [2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[6 5 4]
 [3 2 1]]
[[1]]
[[3 1]
 [4 2]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
[[4 1]
 [5 2]
 [6 3]]


## Transpose Matrix

The transpose of a matrix is a new matrix where the rows and columns have been swapped. I.e. rows become columns and columns become rows.

![Swap Transpose](https://wikimedia.org/api/rest_v1/media/math/render/svg/8a1e10800e0d0e3ffa90917139532cfb8348fc63)
![Swap Transpose](https://wikimedia.org/api/rest_v1/media/math/render/svg/4a92835c45d5cd15dd00a8d90c14bdb4b8150ef0)

Two ways to transpose a matrix:

1. Set the rows equal to the columns and the columns equal the rows
2. Reflect the elements across the main diagonal

![Reflection Transpose](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Matrix_transpose.gif/200px-Matrix_transpose.gif)

A simple way to calculate the transpose by hand is:

1. Rotate the matrix right 90°
2. Reverse the order of elements in each row (e.g. [a b c] becomes [c b a])

Why do we transpose?
* Allows more efficient calculations between matrices
* Building block for other operations like Rotate and Flip

Why more efficient?

* Computers store matrices in row-major order
    * Rows are contiguous in memory
    * Columns are discontiguous
* If repeated operations need to be performed on columns, tranpose improves performance by increasing memory locality

Use cases
* Neural networks - Prepare weights matrix for matrix multiplication
* Fast Fourier Transforms

Some useful properties:

* You can undo a transpose by transposing twice
* For square matrices, the eigenvalues are equal to the eigenvalues of the transpose
* You can test for symmetry if the transpose equals itself


Links
* http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html#matrix-transpose (UPDATE!)
* https://en.wikipedia.org/wiki/Transpose

In [88]:
"""
Swap rows and columns 
[ 1 2 ]  = [ 1 3 ]
[ 3 4 ]    [ 2 4 ]
"""
def get_shape(arr):
    shape = []
    while type(arr) in [list, np.ndarray]:
        shape.append(len(arr))
        arr = arr[0]
    return tuple(shape)
    
def transpose2d(arr):
    rows,cols = len(arr), len(arr[0])
    T = [[arr[r][c] for r in range(rows)] for c in range(cols)]
    return T

def transpose_np(arr):
    return arr.T

In [89]:
for a in arrs:
    print(get_shape(a))
for a in arrs:
    P(a, transpose2d(a))
for a in arrs:
    P(a, transpose_np(a))

(1, 1)
(2, 2)
(3, 3)
(2, 3)
[[1]]
[[1]]
---
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
---
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
---
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
---
[[1]]
[[1]]
---
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
---
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
---
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
---


## Inverse

## Identity

## Orthagonal

## Flip

In [15]:
# Horizonal
def hflip2D(arr):
    pass

# Vertical
def vflip2D(arr):
    pass

## Translate

In [41]:
# Shift

## Elementwise product

## Dot product

* https://betterexplained.com/articles/matrix-multiplication/

## Cross Product

## Intersection

## Union

## Scale

## 3D

In [17]:
# Rotate
# FLip
# Search for value
# Find largest connected group

## Swap Integers (in-place)

In [44]:
def swap_ints(a, b):
    print(a,b)
    b += a
    a += a
    a = (b - a) + a//2
    b = b - a
    print(a,b,'\n---')

In [45]:
swap_ints(2,5)
swap_ints(3,3)
swap_ints(5,3)
swap_ints(-2,3)
swap_ints(0,0)
swap_ints(-1,-5)

2 5
5 2 
---
3 3
3 3 
---
5 3
3 5 
---
-2 3
3 -2 
---
0 0
0 0 
---
-1 -5
-5 -1 
---


## Next